name: Docker Image Build and Publish to GHCR

on:
  push:
    branches:
      - main  # Changer en la branche que vous souhaitez surveiller

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --file Dockerfile \
            --tag ghcr.io/${{ github.repository }}/api:latest \
            .
      
      - name: Push Docker image to GHCR
        run: |
          docker buildx create --use
          docker buildx build \
            --file Dockerfile \
            --tag ghcr.io/${{ github.repository }}/api:latest \
            --push .
